package njalla

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	"github.com/Sighery/gonjalla"
)

// Dynamic records take neither `content` nor `ttl`, but gonjalla.Record
// always serialises both, so requests are built by hand. Njalla generates
// the DDNS update key and exposes it as the record's `content`.
func resourceRecordDynamic() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceRecordDynamicCreate,
		ReadContext:   resourceRecordDynamicRead,
		DeleteContext: resourceRecordDynamicDelete,

		Schema: map[string]*schema.Schema{
			"domain": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "Specifies the domain this record will be applied to.",
			},
			"name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
				DefaultFunc: func() (any, error) {
					return "@", nil
				},
				Description: "Name for the record.",
			},
			"key": {
				Type:        schema.TypeString,
				Computed:    true,
				Sensitive:   true,
				Description: "DDNS update key generated by Njalla.",
			},
		},

		Importer: &schema.ResourceImporter{
			StateContext: resourceRecordDynamicImport,
		},
	}
}

func resourceRecordDynamicCreate(
	ctx context.Context, d *schema.ResourceData, m any,
) diag.Diagnostics {
	config := m.(*Config)

	params := map[string]any{
		"domain": d.Get("domain").(string),
		"type":   "Dynamic",
		"name":   d.Get("name").(string),
	}

	data, err := gonjalla.Request(config.Token, "add-record", params)
	if err != nil {
		return diag.FromErr(err)
	}

	var saved gonjalla.Record
	if err := json.Unmarshal(data, &saved); err != nil {
		return diag.FromErr(err)
	}

	d.SetId(saved.ID)

	return resourceRecordDynamicRead(ctx, d, m)
}

func resourceRecordDynamicRead(
	ctx context.Context, d *schema.ResourceData, m any,
) diag.Diagnostics {
	config := m.(*Config)

	domain := d.Get("domain").(string)

	var diags diag.Diagnostics

	records, err := gonjalla.ListRecords(config.Token, domain)
	if err != nil {
		return diag.FromErr(err)
	}

	for _, record := range records {
		if d.Id() == record.ID {
			d.Set("name", record.Name)
			d.Set("key", record.Content)

			return diags
		}
	}

	d.SetId("")
	return diags
}

func resourceRecordDynamicDelete(
	ctx context.Context, d *schema.ResourceData, m any,
) diag.Diagnostics {
	config := m.(*Config)

	domain := d.Get("domain").(string)

	err := gonjalla.RemoveRecord(config.Token, domain, d.Id())
	if err != nil {
		return diag.FromErr(err)
	}

	var diags diag.Diagnostics
	return diags
}

func resourceRecordDynamicImport(
	ctx context.Context, d *schema.ResourceData, m any,
) ([]*schema.ResourceData, error) {
	domain, id, err := parseImportID(d.Id())
	if err != nil {
		return nil, err
	}

	config := m.(*Config)

	records, err := gonjalla.ListRecords(config.Token, domain)
	if err != nil {
		return nil, fmt.Errorf(
			"Reading records for domain %s failed: %s", domain, err.Error(),
		)
	}

	for _, record := range records {
		if id == record.ID {
			d.SetId(id)
			d.Set("domain", domain)
			d.Set("name", record.Name)
			d.Set("key", record.Content)

			return []*schema.ResourceData{d}, nil
		}
	}

	return nil, fmt.Errorf("Couldn't find record %s for domain %s", id, domain)
}
